### PR TITLE
Fix save_to_file on Macos Ventura when using nsss

### PR DESCRIPTION
**Pull request by codeaye**
This fix waits for the system to finish writing to the file system before continuing.

### CODE REVIEW

**Comment by pm96** [comment]
👍 works

**Comment by maig81** [comment]
Worked for me to.

**Comment by Akul2010** [comment]
Since this is no longer being updated, would you like to join me as I try to maintain this project when I can? Link is here: https://github.com/Akul-AI/rlvoice-1

**Comment by ekalosak** [comment]
@nateshmbhat please consider this for merge - the issue on MacOS is widespread.

**Comment by nateshmbhat** [comment]
thanks for ur contributions 🙏🏻 
merging

**Pull request merged**
