### PR TITLE
fixed issue where NSApp terminate called after endLoop

### PR DESCRIPTION
**Pull request by randdvorak**
The macOS driver uses PyObjC to driver the speech synthesis.   In PyObjC after the event loop is stopped the app calls terminate.  This remedies that by driving the runloop ourselves instead of calling AppHelper.startEventLoop.  Everything else proceeds normally.

### CODE REVIEW

**Review by eriklutwin — APPROVED** [review]
I'm a novice, but making these changes worked for me.  My simple app had a tkinter window and button. Press the button and the app listens for a prompt.  Depending upon the prompt it either says hello, goodbye or get the current weather and says it out loud.  Before the changes, the app just quit.  Now it does not and I can press the button and make another prompt.

**Comment by ekalosak** [comment]
@nateshmbhat any thoughts on this PR?

**Comment by holytony** [comment]
> The macOS driver uses PyObjC to driver the speech synthesis. In PyObjC after the event loop is stopped the app calls terminate. This remedies that by driving the runloop ourselves instead of calling AppHelper.startEventLoop. Everything else proceeds normally.

This bug is such pain in the ass, now its 2024, it's still here

**Comment by technisculpt** [comment]
you could instead use the apple speech API using subprocess as I implemented [here](https://github.com/technisculpt/blender-text-to-speech/edit/main/Text%20to%20Speech/text_to_sound.py).

Here is a simplified example:

```
from sys import platform
import subprocess
import pyttsx3

def mac_engine(_text, _voice, _rate, _path):
    subprocess.call(["say", _text, "-o", _path, f"--rate={_rate}", "-v", _voice])

def engine(_text, _voice, _rate, _path):
    engine = pyttsx3.init()
    voices = engine.getProperty('voices') 
    engine.setProperty('voice', voices[int(_voice)].id)
    engine.setProperty('rate', int(_rate))
    engine.save_to_file(_text, _path)
    engine.runAndWait() 
   
def text_to_speech(text, voice, rate, path):
    if sys.platform == "darwin":
        mac_engine(text, voice, rate, path)
    else:
        engine(text, voice, rate, path)
```

**Comment by holytony** [comment]
> @holytony you could instead use the apple speech API using subprocess as I implemented [here](https://github.com/technisculpt/blender-text-to-speech/edit/main/Text%20to%20Speech/text_to_sound.py).
> 
> Here is a simplified example:
> 
> ```
> from sys import platform
> import subprocess
> import pyttsx3
> 
> def mac_engine(_text, _voice, _rate, _path):
>     subprocess.call(["say", _text, "-o", _path, f"--rate={_rate}", "-v", _voice])
> 
> def engine(_text, _voice, _rate, _path):
>     engine = pyttsx3.init()
>     voices = engine.getProperty('voices') 
>     engine.setProperty('voice', voices[int(_voice)].id)
>     engine.setProperty('rate', int(_rate))
>     engine.save_to_file(_text, _path)
>     engine.runAndWait() 
>    
> def text_to_speech(text, voice, rate, path):
>     if sys.platform == "darwin":
>         mac_engine(text, voice, rate, path)
>     else:
>         engine(text, voice, rate, path)
> ```

this actually works. also the pyttsx3 is blocking when it speaks, during which the UI would freeze when its called, even creating a new thread would't solve the problem, however, when I call subprocess say in a new thread, it works flawlessly, thank a lot.

**Pull request merged**
