### PR TITLE
PEP 621: Migrate from setup.py to pyproject.toml

### LINKED ISSUE #337: `python setup.py` and the use of `setup.py` as a command line tool are deprecated
`python setup.py` and the use of `setup.py` as a command line tool are deprecated.
* https://packaging.python.org/en/latest/discussions/setup-py-deprecated/

https://github.com/search?q=repo%3Anateshmbhat%2Fpyttsx3+setup.py&type=code

https://github.com/nateshmbhat/pyttsx3/blob/e8a803c4ed3011cc7f158d5116acaeacdbcbc438/makefile#L6
https://github.com/nateshmbhat/pyttsx3/blob/e8a803c4ed3011cc7f158d5116acaeacdbcbc438/.github/workflows/pythonpublish.yml#L35-L36

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #337
~Blocked by #338~
* #337
* ~#338~

### How
Migrate `setup.py` to `setup.cfg` using [setuptools-py2cfg](https://pypi.org/project/setuptools-py2cfg) plus manual modifications.  Use [setup-cfg-fmt](https://pypi.org/project/setup-cfg-fmt) to format the results.

Migrate settings from `setup.cfg` into `pyproject.toml` using [ini2toml](https://pypi.org/project/ini2toml) to do the file conversion and running [pyproject-fmt](https://pypi.org/project/pyproject-fmt) and then [validate-pyproject](https://github.com/abravalheri/validate-pyproject) to validate the results.
```bash
git checkout -b setuptools-py2cfg
pipx run setuptools-py2cfg > setup.cfg
pipx run ini2toml setup.cfg -o pyproject.toml
git add pyproject.toml
pipx run validate-pyproject pyproject.toml
code pyproject.toml  # Make any suggested changes
pipx run pyproject-fmt pyproject.toml
pipx run validate-pyproject pyproject.toml
git rm --force setup.cfg
git rm setup.py
code makefile .github/workflows/pythonpublish.yml
python3 -m venv .venv
source .venv/bin/activate
pipx run build  # —> Successfully built pyttsx3-2.98.tar.gz and pyttsx3-2.98-py3-none-any.whl
ls dist  # —> pyttsx3-2.98-py3-none-any.whl    pyttsx3-2.98.tar.gz
pip install --editable .
git commit -am"PEP 621: Migrate from setup.py to pyproject.toml"
git push
```
### Why
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
> We recommend users expose as much as possible configuration in a more declarative way via the [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) or [setup.cfg](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), and keep the setup.py minimal with only the dynamic parts (or even omit it completely if applicable).

From `validate-pyproject` README:
> With the approval of [PEP 517](https://www.python.org/dev/peps/pep-0517/) and [PEP 518](https://www.python.org/dev/peps/pep-0518/), the Python community shifted towards a strong focus on standardization for packaging software, which allows more freedom when choosing tools during development and make sure packages created using different technologies can interoperate without the need for custom installation procedures.

> This shift became even more clear when [PEP 621](https://www.python.org/dev/peps/pep-0621/) was also approved, as a standardized way of specifying project metadata and dependencies.

> `validate-pyproject` was born in this context, with the mission of validating `pyproject.toml` files, and making sure they are compliant with the standards and PEPs.

### CODE REVIEW

**Comment by willwade** [comment]
Oh wow. That’s great. I’ll do a pr for #338 after we do this.

**Comment by cclauss** [comment]
ALWAYS add tests (#338) before making changes (like this PR) instead of vice versa.  The before/after test runs can be enlightening.

**Comment by nateshmbhat** [comment]
Ya wud be good to merge the tests first before this PR is merged imo

**Comment by willwade** [comment]
Now tests are merged is this good to go? 

I have a feeling we should do a review of tests once we do #348 it should pass all tests

**Comment by cclauss** [comment]
Ready for review.

**Comment by cclauss** [comment]
Can we remove any instances of `skipif`?!?
* https://github.com/search?q=repo%3Anateshmbhat%2Fpyttsx3+skipif&type=code

**Comment by willwade** [comment]
Yep. We should be able to

I think we need to make a change too. Espeak needs to run on all platforms. It's fiddly though as espeak-ng needs to be on all platforms 

Not massively important. Linux is the main target

**Comment by willwade** [comment]
try removing these skips now.. im hoping this should be ok..

**Pull request merged**
