### PR TITLE
Fix a bug introduced in #57

### PR DESCRIPTION
**Pull request by fourjr**
As raised by @Gurto and @jeffreyscurtis in #57, runAndWait gets stuck indefinitely.

> not sure why this PR is so funky

### CODE REVIEW

**Comment by nateshmbhat** [comment]
Is it fixed now?

**Comment by fourjr** [comment]
yes

**Comment by rahulmisras** [comment]
i checked this. And i get the file saved at given location however file is always 1kb of size and does not play anything

**Comment by fourjr** [comment]
Unable to reproduce

**Comment by rahulmisras** [comment]
here is my code let me know what am i doing wrong.

import pyttsx3
engine = pytts3.init()
filesave = "D:\\tts\\wavfile\\tts.wav"
f = open("D:\\tts\\tts.text", "r")
fileRead = f.read()
engine.save_to_file(fileRead,filesave,'rahul')

it saves a file but if 46 bytes and does not play anything at all.

**Comment by fourjr** [comment]
Did you read the documentation? The signature for save_to_file is `save_to_file(text, filename)`.

**Comment by rahulmisras** [comment]
import pyttsx3
engine = pytts3.init()
filesave = "D:\tts\wavfile\tts.wav"
f = open("D:\tts\tts.text", "r")
fileRead = f.read()
engine.save_to_file(fileRead,filesave) 

still the file size is same and does not play anything in any player. I even try to convert it with PYdub it says file has no header and corrupted.

**Comment by tamoyahopkins** [comment]
All I have a similar problem.  I have everything wired up according to examples I have seen and am passing a text file to pyttsx3.  The file that saves is always very small ~< 3 seconds or so long, even though the text input

 is much longer.  Any idea why this is happening?  The audio file saved does work, but never captures the full text information sent to it. 

Please let me know why the engine is not saving files with recording of full speech data.  Any suggestions would be greatly appreciated.  

---
Code below: 

`
import pyttsx3
import time

text = '''Take a closer look at Redbox On Demand. Can't see our images? click here. Rent movies online at Redbox.com, where you can reserve and preview new DVDs, Blu Rays and games. Take a closer look at Redbox On Demand. Can't see our images? click here. Big Hits On Demand More Movies On Demand Family Favorites On Demand Best Games **NO PURCHASE OR PAYMENT NECESSARY; PURCHASE OR PAYMENT WILL NOT INCREASE ODDS OF WINNING. Open to legal residents of the 50 United States and D.C. who are at least 18 (or age of majority in their jurisdiction of residence, whichever is older) upon entry. Void where prohibited. “Sweepstakes Period” is 12:00:01am CT on January 2, 2018 to 11:59:59pm CT on January 31, 2018. 
'''

def speak(audio_id, text, lang='en'):
    start = time.time()
    engine = pyttsx3.init()
    filename = f'testTTS2/audio_{audio_id}.mp3'
    print(text)
    engine.save_to_file(text, filename)
    engine.runAndWait()
    print(f'------SAVED FILE {filename} - EXECUTION TIME {str(time.time() - start)} --------')

speak(0, text)`

---

**Pull request merged**
