### PR TITLE
Implement Linux Support in save_to_file 

### PR DESCRIPTION
**Pull request by fourjr**
Drawing inspiration from #7 and DeepHorizons, the following is my implementation of Linux support into `save_to_file`.

### CODE REVIEW

**Comment by fourjr** [comment]
@nateshmbhat PR is ready for review/merge

**Comment by fourjr** [comment]
@nateshmbhat PR is ready for review/merge

**Comment by fourjr** [comment]
@nateshmbhat PR is ready for review and merge

**Comment by khushbu-mulani** [comment]
@fourjr @nateshmbhat I tried `save_to_file` on linux which doesn't seem to work. Any suggestions?

**Pull request merged**
