### PR TITLE
Remove Python 2 compatibility module six

### PR DESCRIPTION
**Pull request by cclauss**
Remove https://pypi.org/project/six because compatibility with legacy Python 2 is no longer useful.
* Python 2 died 1,752 days ago on 1/1/2020.

### CODE REVIEW

**Comment by willwade** [comment]
Im really good with this. But @nateshmbhat you may have other feelings. If you can say yes or no - that would be handy as it will conflict with other PR's ive got lined up

**Comment by willwade** [comment]
Could do with merging this. Then making sure I don't reintroduce in  future PRs

**Comment by nateshmbhat** [comment]
This looks fine. We can go ahead 🙏🏻.
Thanks for these contributions ✨

**Comment by willwade** [comment]
> This looks fine. We can go ahead 🙏🏻. Thanks for these contributions ✨

Thanks! And thanks too @cclauss - I’m learning a lot from your PRs

@cclauss  I note this is still draft. Are you happy with it? It will fail on Linux tests but that’s more to do with bugs we will fix in #338

**Comment by cclauss** [comment]
I made some tests for this which I can add tonight.

**Comment by willwade** [comment]
Merging this 🤞

**Pull request merged**
