### PR TITLE
ruff check --select=ALL --ignore=COM812,D212,ERA001,T201 --fix

### PR DESCRIPTION
**Pull request by cclauss**
% `ruff check --select=ALL --ignore=COM812,D212,ERA001,T201 --fix --unsafe-fixes`

The second half of the automatic fixes and modernizations in #377.  This adds `--unsafe-fixes` which require more review.
* #377

### CODE REVIEW

**Review by willwade — COMMENTED** [review]
Yeah I see what you mean about needing a bit more of a review. I need to read up what contextlib does ..

**Comment by cclauss** [comment]
https://docs.astral.sh/ruff/rules/suppressible-exception/

**Comment by cclauss** [comment]
Ready for your review.

**Comment by willwade** [comment]
I'm good with this

**Comment by willwade** [comment]
NB: Id be up for adding in COM812 and migrating T201 to logger.debug and ERA001 - id be up for migrating these commmented out code lines to be full comments

**Comment by cclauss** [comment]
Let's leave these ignores in place for now.  I ignore them all for good reasons.  The commas add tons of unneeded lines.  Commented out code is fine while we are still experimenting.  Rushing to logging everywhere is not our highest priority.

**Pull request merged**
